### PR TITLE
Bump rdkafka version

### PR DESCRIPTION
**Pull request by rkudryashov**
This allows working with latest Kafka distributions

### CODE REVIEW

**Comment by jcrossley3** [comment]
Thanks for this, but just to be clear: the "caret requirement" of `^0.25` wouldn't prevent a user from updating to `0.28` would it?

**Comment by rkudryashov** [comment]
If I understand the question correctly, then it shouldn't prevent the updating because the suggested changes will require ```0.28``` as a minimal version. A user may be needed to update explicit `rdkafka` dependency (if one has it) to be compatible with ```cloudevents```.

**Comment by jcrossley3** [comment]
I just tried updating only the example to be `0.28` but that failed due to a conflicting transitive dep of `rdkafka-sys`. It seems `0.25` => `v3.0.0+1.6.0` and `0.26` => `v4.2.0+1.8.2`. So maybe the right thing is to update the root to `^0.26` and the example to `^0.28`?

I don't know enough about `rdkafka` users to know whether anyone will be upset that we no longer support `0.25`. Do you have an opinion? ;)

**Comment by rkudryashov** [comment]
Yep, I think the latter is not a problem :)

Could you also try to update the root to `0.28`?

Also, if `0.26` => `v4.2.0+1.8.2`, then perhaps `0.28` depends on the same version of `rdkafka-sys`. So there is no difference use `0.26` or `0.28`

**Comment by jcrossley3** [comment]
> Could you also try to update the root to `0.28`?

Yeah, that's what you have in this PR. CI ran it without issue, and it built for me locally fine.

> Also, if `0.26` => `v4.2.0+1.8.2`, then perhaps `0.28` depends on the same version of `rdkafka-sys`. So there is no difference use `0.26` or `0.28`

Yes, all versions since 0.26 use the same `rdkafka-sys` version.

I'm guessing since there's no official release of rdkafka anyway, setting both to 0.28 (the current latest) is fine.

**Comment by rkudryashov** [comment]
So could that be merged? :)

**Comment by jcrossley3** [comment]
Oh, sorry. :smile:

**Pull request merged**
