### PR TITLE
Fix tests after refactoring URIRef

### PR DESCRIPTION
**Pull request by ctron**

### CODE REVIEW

**Comment by ctron** [comment]
Looks like I broke a bunch of tests in PR #115 and the CI didn't show that (at least to me) … sorry for that, this should fix it.

**Comment by slinkydeveloper** [comment]
@ctron any updates on this one? It seems to me, this still doesn't fix all the tests

**Comment by ctron** [comment]
> @ctron any updates on this one? It seems to me, this still doesn't fix all the tests

I will take a look.

**Comment by slinkydeveloper** [comment]
Nice, thanks for fixing it!

**Comment by ctron** [comment]
> Nice, thanks for fixing it!

Thanks for nagging me :grin: … I am sorry, I really forgot about this one.

**Pull request merged**
