### PR TITLE
Change unused dependency to dev_dependency

### PR DESCRIPTION
**Pull request by tottoto**
actix_rt is only used in tests.

Signed-off-by: tottoto <tottotodev@gmail.com>

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
Do we really need `actix_rt` or can we do like https://github.com/cloudevents/sdk-rust/pull/102?

**Comment by tottoto** [comment]
I think we need `actix_rt` because `actix_web` does not have the alternative to `actix_rt::test`.

The [actix-web's official document for testing](https://github.com/actix/actix-website/blob/v3/examples/testing/src/main.rs#L25) uses `actix_rt::test`.

**Comment by slinkydeveloper** [comment]
Ok then I'm fine with it

**Comment by slinkydeveloper** [comment]
Thanks for your contribution!

**Comment by tottoto** [comment]
Related issue(https://github.com/actix/actix-web/issues/1669).

**Pull request merged**
